[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38', 'py39', 'py310', 'py311']
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
force-exclude = '''
venv
'''

[tool.isort]
profile = "black"
line_length = 120
known_third_party = [
    "flask",
    "django",
    "numpy",
    "pandas",
    "fastapi",
]
force_single_line = true

[tool.pytest.ini_options]
asyncio_mode = "auto"  # test-code 작성시 비동기 데코레이터 안써도 됨 pytest.mark.asyncio
